import { useState } from "react";
import { motion } from "framer-motion";
import { ChevronDown } from "lucide-react";

const reviewPrograms = [
{ id: 'appraiser', shortName: 'REALEX', name: 'Appraiser Review', description: 'Master the fundamental principles, valuation methodologies, and advanced practices required for the licensure exam.', modules: [{ number: '01', weeks: 'Phase 1', title: 'Foundations', description: 'Introduces the fundamental principles of real property, valuation standards, ethics, and the legal framework governing professional appraisers.', topics: ['Philippine Valuation Standards (PVS)', 'Real Estate Principles', 'Market Analysis and Economic Concepts Relevant to Valuation', 'More ...'] }, { number: '02', weeks: 'Phase 2', title: 'Valuation Methods & Practice', description: 'Covers the primary methodology and practical techniques used to value property, including inspection processes, sales comparison, and cost calculations.', topics: ['Elements of Value, Appraisal Process, and Scope of Work', 'Data Gathering and Property Inspection', 'Cost Approach', 'More ...'] }, { number: '03', weeks: 'Phase 3', title: 'Advanced Applications & Reviews', description: 'Explores complex valuation concepts such as income capitalization, financial yield math, special-purpose properties, and regulatory compliance reviews.', topics: ['Income Capitalization Approach', 'Appraisal Mathematics', 'Special-Purpose Properties', 'More ...'] }, { number: '04', weeks: 'Phase 4', title: 'Mock Exams & Intensive Reviews', description: 'Combines rigorous mock testing with detailed evaluation and targeted writing reviews to master the final appraisal report.', topics: ['Fundamentals; Discussion of Mock Exam', 'Weak Areas Review', 'Appraisal Report Writing, Reconciliation, and Final Value Opinion'] }, { number: '05', weeks: 'Phase 5', title: 'Final Coaching', description: 'The ultimate preparation session designed to lock in final strategies right before the licensure exam.', topics: ['Final Coaching and Exam Strategy'] }] },
{ id: 'broker', shortName: 'REBLEx', name: 'Broker Review', description: 'Master brokerage operations, land legal systems, project development, and mock testing required for the licensure exam.', modules: [{ number: '01', weeks: 'Phase 1', title: 'Foundations', description: 'Master the principles, roles, and responsibilities of a real estate broker.', topics: ['Fundamentals of Property Ownership', 'Code of Ethics and Responsibilities', 'Real Estate Laws and Taxation', 'Subdivision Developments', 'More ..'] }, { number: '02', weeks: 'Phase 2', title: 'Practices & Technical Topics', description: 'Focuses on the practical application of brokerage operations, including zoning, environmental principles, finance, and basic appraisal.', topics: ['Real Estate Finance and Economics', 'Basic Appraisal for Real Estate Brokers', 'Basic Principles of Ecology', 'More ..'] }, { number: '03', weeks: 'Phase 3', title: 'Reinforcement & Reviews', description: 'Provides systematic, topic-by-topic reviews of foundational and practical concepts to reinforce understanding before testing begins.', topics: ['Review: Subdivision Development', 'Review: Condominium Concepts', 'Review: Urban and Land Use', 'More ..'] }, { number: '04', weeks: 'Phase 4', title: 'Mock Exams & Intensive Reviews', description: 'An intensive testing and diagnostic phase featuring simulated board exams, weak-area targeting, and focused case-study applications.', topics: ['Professional Practice', 'Case Studies and Applications', 'Appraisal Intensive Review', 'Brokerage Practice Review'] }, { number: '05', weeks: 'Phase 5', title: 'Final Coaching', description: 'A final high-yield review session focused on exam-taking strategies and critical master summaries.', topics: ['Pre-Exam Master Review', 'Final Coaching and Exam Strategy'] }] },
{ id: 'consultant', shortName: 'RECLEx', name: 'Consultant Review', description: 'High-level real estate consulting preparation focused on market research, project feasibility studies (PFS), legal frameworks, and board review.', modules: [{ number: '01', weeks: 'Phase 1', title: 'Foundations', description: 'Outlines the high-level role of consulting, diving into legal land systems, economic factors, and professional ethical duties.', topics: ['Nature of Real Estate Consulting', 'Real Estate Economics', 'Land Management System', 'More ...'] }, { number: '02', weeks: 'Phase 2', title: 'Market, Legal, and Financial Framework', description: 'Analyzes the core economic drivers, supply-demand research, feasibility concepts, and site selections that support advisory services.', topics: ['Zoning and Development Controls', 'Project Concept Development', 'Legal and Institutional Analysis; Permits and Compliance', 'More ...'] }, { number: '03', weeks: 'Phase 3', title: 'Project Feasibility Study and Consultancy Practice', description: 'A highly technical phase focused on conducting, writing, and defending a professional Project Feasibility Study (PFS), including financial modeling and sensitivity testing.', topics: ['Financial Feasibility I', 'Financial Feasibility II', 'Sensitivity Analysis, Risk Analysis, and Scenario Testing', 'More ...'] }, { number: '04', weeks: 'Phase 4', title: 'Mock Exams and Intensive Reviews', description: 'Features successive trial exams mirroring the official consultant board topics alongside applied problem-solving drills.', topics: ['PFS and Case Studies; Discussion of Mock Exam', 'Weak Areas Review; Integrated Case Drills; Applied Problem Solving', 'Full Mock Examination; Mock Examination Discussion'] }, { number: '05', weeks: 'Phase 5', title: 'Final Coaching', description: 'A comprehensive wrap-up program covering final test tactics and high-level summaries for prospective consultants.', topics: ['Final Comprehensive Review', 'Final Coaching and Exam Strategy'] }] },
];

export default function Syllabus() {
  const [selectedProgram, setSelectedProgram] = useState(reviewPrograms[0]);
  const [openIndex, setOpenIndex] = useState(null);

  const selectProgram = (program) => {
    setSelectedProgram(program);
    setOpenIndex(null);
  };

  return <section id="curriculum" className="py-24 md:py-32">
    <div className="max-w-4xl mx-auto px-6 md:px-10">
      <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: 0.6 }} className="text-center mb-12">
        <span className="text-[#B39255] font-sans text-sm tracking-[0.25em] uppercase font-medium">The Path</span>
        <h2 className="mt-4 font-serif text-[#1B432E] text-3xl md:text-display-sm font-bold">Review Curriculum</h2>
        <p className="mt-4 text-[#1B432E]/60 font-sans text-lg max-w-xl mx-auto leading-relaxed">Choose a service to explore its dedicated board-exam review curriculum.</p>
      </motion.div>

      <div className="grid sm:grid-cols-3 gap-3 mb-12" role="tablist" aria-label="Review programs">
        {reviewPrograms.map((program) => <button key={program.id} type="button" role="tab" aria-selected={selectedProgram.id === program.id} onClick={() => selectProgram(program)} className={`rounded-lg border p-4 text-left transition ${selectedProgram.id === program.id ? "border-[#B39255] bg-[#1B432E] text-[#F9F9F7] shadow-lg" : "border-[#1B432E]/15 text-[#1B432E] hover:border-[#B39255]/60"}`}><span className="font-serif text-xl font-bold">{program.shortName}</span><span className={`block mt-1 text-xs leading-relaxed ${selectedProgram.id === program.id ? "text-[#F9F9F7]/65" : "text-[#1B432E]/55"}`}>{program.name.replace(`${program.shortName} - `, "")}</span></button>)}
      </div>

      <div className="mb-8"><p className="text-[#B39255] font-sans text-xs font-medium tracking-widest uppercase">{selectedProgram.shortName}</p><h3 className="font-serif text-[#1B432E] text-2xl md:text-3xl font-bold mt-1">{selectedProgram.name}</h3><p className="text-[#1B432E]/60 mt-2">{selectedProgram.description}</p></div>
      <div className="relative"><div className="absolute left-6 md:left-8 top-0 bottom-0 w-px bg-gradient-to-b from-[#B39255]/20 via-[#B39255]/40 to-[#B39255]/20" />
        {selectedProgram.modules.map((module, index) => {
          const isOpen = openIndex === index;
          return <motion.div key={`${selectedProgram.id}-${module.number}`} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.3, delay: index * 0.05 }} className="relative pl-16 md:pl-20 py-6"><div className={`absolute left-[18px] md:left-[26px] top-8 w-3 h-3 rounded-full border-2 ${isOpen ? "bg-[#B39255] border-[#B39255] scale-125" : "bg-[#F9F9F7] border-[#B39255]/50"}`} /><button type="button" onClick={() => setOpenIndex(isOpen ? null : index)} className="w-full text-left group"><div className="flex items-start justify-between gap-4"><div><span className="text-[#B39255] text-xs font-medium tracking-widest">{module.weeks}</span><h4 className="font-serif text-[#1B432E] text-xl md:text-2xl font-bold mt-1 group-hover:text-[#B39255] transition-colors"><span className="text-[#B39255]/40 mr-2">{module.number}.</span>{module.title}</h4></div><ChevronDown className={`w-5 h-5 text-[#B39255] mt-6 shrink-0 transition-transform ${isOpen ? "rotate-180" : ""}`} /></div></button><div className={`overflow-hidden transition-all duration-300 ${isOpen ? "max-h-60 opacity-100 mt-3" : "max-h-0 opacity-0"}`}><p className="text-[#1B432E]/60 text-[15px] leading-relaxed mb-3">{module.description}</p><div className="flex flex-wrap gap-2">{module.topics.map((topic) => <span key={topic} className="px-3 py-1 text-xs font-medium text-[#1B432E]/70 bg-[#1B432E]/[0.05] rounded-full">{topic}</span>)}</div></div>{index < selectedProgram.modules.length - 1 && <div className="border-b border-[#1B432E]/[0.06] mt-6" />}</motion.div>;
        })}
      </div>
    </div>
  </section>;
}
